name: cs109a

channels:
- conda-forge

dependencies:
# - asyncio # comes with python standard library
- aiohttp
- beautifulsoup4
- jupyterlab
- lxml
- matplotlib
- networkx
- numpy
- pandas
- pillow
- pip
- python>=3.10
- requests
- scipy
- scikit-learn
- seaborn
- selenium
- statsmodels
- pip:
  - nbopen
  - otter-grader
